version: "3.9"

services:
  api:
    build: ./api
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./api/src:/app/src
      - ./api/requirements.txt:/app/requirements.txt
    environment:
      - FLASK_APP=src/main.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run
